const styles = {
  outerHeader: {
    height: 62,
    width: "100%",
    background: "#292929",
    border: "2px solid rgba(255, 230, 99, 0.2)",
    justifyContent: "space-between",
    padding: 10,
    borderRadius: 10,
    position: "sticky",
    top: 0,
    zIndex: 1000,
    margin: "0 auto",
    boxShadow: "10.3472px 11.4969px 72.4307px rgba(0, 0, 0, 0.24)",
    "@media(max-width: 600px)": {
      height: 80,
      position: "relative",
      zIndex: 0,
      display: "none !important",
    },
  },
  title: {
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: 25,
    color: "#FFF",
    textTransform: "uppercase",
  },
  plantLocation: {
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: 12,
    lineHeight: "20px",
    color: "#536471",
    marginLeft: 8,
  },
  initialName: {
    width: 42,
    height: 42,
    background: "#F0F4FA",
    borderRadius: 72,
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: 12,
    lineHeight: "18px",
    color: "#26184D",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  menuOuter: {
    width: 200,
    background: "#FFFFFF",
    border: "1px solid #DDE5EC",
    boxSizing: "border-box",
    boxShadow: "0px 4px 12px rgba(78, 89, 109, 0.05)",
    borderRadius: 8,
    marginTop: 40,
  },
  menuItem: {
    height: 32,
    padding: "6px 16px",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: 12,
    lineHeight: "20px",
    color: "#536471",
  },
  menuProfile: {
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: 14,
    lineHeight: "24px",
    color: "#536471",
  },
  menuEmail: {
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: 12,
    lineHeight: "20px",
    color: "#8C9AA4",
  },
  menuInner: {
    height: 60,
    padding: "0 16px",
    borderBottom: "1px solid #E4EAF5",
    marginBottom: 8,
  },
  profileTitle: {
    color: "#536471",
    textTransform: "uppercase",
    fontSize: 14,
    fontWeight: 600,
  },
};

export default styles;
